function updateTab() {
  tab = event.target.id
  console.log(tab)
  if (tab === "tab1" || tab === undefined) {
    document.getElementById("tab1").style.color = "#707070"
    document.getElementById("tab2").style.color = "white"
    document.getElementById("tab3").style.color = "white"
    document.getElementById("tab4").style.color = "white"
    document.getElementById("option1").innerHTML = "Find Nearby Doctor Instantly"
    document.getElementById("option2").innerHTML = "24/7 Booking Online Anytime, Anywhere"
    document.getElementById("option3").innerHTML = "Appointment Reminder"
    document.getElementById("option4").innerHTML = "Reduced Waiting Time"
    document.getElementById("option5").innerHTML = "Online Marketplace For Employee Benefits"
    document.getElementById("container6").style.display = "initial"
    document.getElementById("option6").innerHTML = "It's Free"
    document.getElementById("option7").innerHTML = "Rewarding you for Staying Active"
    document.getElementById("image1").src = "/imgs/doctorNearby.svg"
    document.getElementById("image2").src = "/imgs/bookOnline.svg"
    document.getElementById("image3").src = "/imgs/appointment.svg"
    document.getElementById("image4").src = "/imgs/reducedTime.svg"
    document.getElementById("image5").src = "/imgs/marketplace.svg"
    document.getElementById("image6").src = "/imgs/free.svg"
    document.getElementById("image7").src = "/imgs/stayingActive.svg"
  } else if (tab === "tab2") {
    document.getElementById("tab2").style.color = "#707070"
    document.getElementById("tab1").style.color = "white"
    document.getElementById("tab3").style.color = "white"
    document.getElementById("tab4").style.color = "white"
    document.getElementById("option1").innerHTML = "List Your Practice Online"
    document.getElementById("option2").innerHTML = "Attract New Patients"
    document.getElementById("option3").innerHTML = "24/7 Online Appointment Scheduling"
    document.getElementById("option4").innerHTML = "Optimize Appointment Scheduling"
    document.getElementById("option5").innerHTML = "Reduce No Show Patient Appointment Reminder"
    document.getElementById("container6").style.display = "none"
    document.getElementById("option7").innerHTML = "Online Marketplace For Employee Benefits"
    document.getElementById("image1").src = "/imgs/health1.svg"
    document.getElementById("image2").src = "/imgs/health2.svg"
    document.getElementById("image3").src = "/imgs/health3.svg"
    document.getElementById("image4").src = "/imgs/health4.svg"
    document.getElementById("image5").src = "/imgs/health5.svg"
    document.getElementById("image7").src = "/imgs/health6.svg"
  } else if (tab === "tab3") {
    document.getElementById("tab3").style.color = "#707070"
    document.getElementById("tab2").style.color = "white"
    document.getElementById("tab1").style.color = "white"
    document.getElementById("tab4").style.color = "white"
    document.getElementById("option1").innerHTML = "Optimize Human Capital"
    document.getElementById("option2").innerHTML = "Attract New Patients"
    document.getElementById("option3").innerHTML = "24/7 Online Appointment Scheduling"
    document.getElementById("option4").innerHTML = "Highly Scalable System"
    document.getElementById("option5").innerHTML = "Analytics"
    document.getElementById("container6").style.display = "none"
    document.getElementById("option7").innerHTML = "Online Marketplace For Employee Benefits"
    document.getElementById("image1").src = "/imgs/hospital1.svg"
    document.getElementById("image2").src = "/imgs/hospital2.svg"
    document.getElementById("image3").src = "/imgs/hospital3.svg"
    document.getElementById("image4").src = "/imgs/hospital4.svg"
    document.getElementById("image5").src = "/imgs/hospital5.svg"
    document.getElementById("image7").src = "/imgs/hospital6.svg"
  } else if (tab === "tab4") {
    document.getElementById("tab4").style.color = "#707070"
    document.getElementById("tab2").style.color = "white"
    document.getElementById("tab3").style.color = "white"
    document.getElementById("tab1").style.color = "white"
    document.getElementById("option1").innerHTML = "Simplify Information Distribution"
    document.getElementById("option2").innerHTML = "Optimize Employee Productivity"
    document.getElementById("option3").innerHTML =
      "Support Management of Employees’ Preventive Care & Wellness Program"
    document.getElementById("option4").innerHTML = "Analytics"
    document.getElementById("option5").innerHTML = "Monitor Employee Benefits"
    document.getElementById("container6").style.display = "none"
    document.getElementById("option7").innerHTML = "Online Marketplace For Employee Benefits"
    document.getElementById("image1").src = "/imgs/company1.svg"
    document.getElementById("image2").src = "/imgs/company2.svg"
    document.getElementById("image3").src = "/imgs/company3.svg"
    document.getElementById("image4").src = "/imgs/company4.svg"
    document.getElementById("image5").src = "/imgs/company5.svg"
    document.getElementById("image7").src = "/imgs/company6.svg"
  }
}
document.getElementById("tab1").style.color = "#707070"
document.getElementById("option1").innerHTML = "Find Nearby Doctor Instantly"
document.getElementById("option2").innerHTML = "24/7 Booking Online Anytime, Anywhere"
document.getElementById("option3").innerHTML = "Appointment Reminder"
document.getElementById("option4").innerHTML = "Reduced Waiting Time"
document.getElementById("option5").innerHTML = "Online Marketplace For Employee Benefits"
document.getElementById("option6").innerHTML = "It's Free"
document.getElementById("option7").innerHTML = "Rewarding you for Staying Active"
